config/routes.rb
HmzFoods::Application.routes.draw do
  devise_for :users

  get "onion" => "homes#onion", :as => "onion"
  get "maize" => "homes#maize", :as => "maize"
  get "about" => "homes#about", :as => "about"
  get "contact" => "homes#contact", :as => "contact"
  get "potato" => "homes#potato", :as => "potato"
  get "rice" => "homes#rice", :as => "rice"

    resources :homes do
      collection do
        post 'message'        
      end
    end

    resources :machines
    resources :categories
  
    resources :categories do
      resources :machines
    end

  root :to => 'homes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :machines
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  attr_accessible :description, :image, :name,:category_id, :url
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :call_categories


  def call_categories
  	@categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(params[:category])
		@category.save
		redirect_to root_url
	end

	def show
		@category = Category.find(params[:id])
		@machines = @category.machines
		@categories = Category.all
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		@category.update_attributes(params[:category])
		flash[:success] = "Successfully updated."
		redirect_to root_url
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
		@categories = Category.all
	end

	def about
	end

	def contact
	end

	def potato
	end

	def onion
	end

	def maize
	end

	def message
		name = params["name"]
		email = params["email"]
		message = params["message"]
		UserMailer.registration_confirmation(name,email,message).deliver
		redirect_to contact_path
	end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController

	def new
		@machine = Machine.new
	end

	def create 
		@machine = Machine.new(params[:machine])
		@machine.save
		redirect_to root_url
	end

	def show
		@categories = Category.all
		@machine = Machine.find(params[:id])
	end

	def edit
		@machine = Machine.find(params[:id])
	end

	def update
		@machine = Machine.find(params[:id])
		@machine.update_attributes(params[:machine])
		flash[:success] = "Successfully updated."
		redirect_to root_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_class(ctrl_name, act_name)
		controller_name == ctrl_name and action_name == act_name ? "active" : ""	
	end

	def active_class_dous(ctrl1_name, act1_name, ctrl2_name, act2_name)
		(controller_name == ctrl1_name and action_name == act1_name) || (controller_name == ctrl2_name and action_name == act2_name) ? "active" : ""	
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/categories/edit.html.erb
<div class="well" style="width: 36%;margin-top: 2%;margin-left: 29%;">
	<%= form_for @category, :html => {:multipart => true} do |f| %>
	  <p>
	    <%= f.label "Category Name" %><br />
	    <%= f.text_field :name, class: "form-control" %>
	  </p>
	  <br /><br />
	  <p><%= f.submit  class: "btn btn-primary"%></p>
	<% end %>
</div>
<br /><br />

app/views/categories/new.html.erb
<div class="well" style="width: 36%;margin-top: 2%;margin-left: 29%;">
	<%= form_for @category, :html => {:multipart => true} do |f| %>
	  <p>
	    <%= f.label "Category Name" %><br />
	    <%= f.text_field :name, class: "form-control" %>
	  </p>
	  <br /><br />
	  <p><%= f.submit  class: "btn btn-primary"%></p>
	<% end %>
</div>
<br /><br />

app/views/categories/show.html.erb
<div id="content" class="col-md-9 col-sm-9 col-xs-12">
  <div class="row"> 
    <% @machines.each do |machine|%>       
      <div class="col-sm-4 col-lg-4 col-md-4 col-sm-height" style="margin-bottom: 5px;     min-height: 400px; ">
        <div class="thumbnail">
            <%= image_tag machine.image_url.to_s, class: "img-responsive", alt: "image description" %>
            <div class="caption" style="height: auto;">  
               <%= link_to "see more", machine_path(machine.id), class: "btn btn-primary pull-right"%>
                <h4><strong><%= machine.name%></strong></h4>
              <% if user_signed_in? %>
            <%= link_to "edit", edit_machine_path(machine.id)%>
            <% end %>
            </div>
            
        </div>
      </div>
    <% end %>  
  </div>
</div>

app/views/homes/about.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->  
<head>
    <title>About Us</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    
</head> 

<body>

<%= render "header"%>  

<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">About Us</h1>
        <!-- <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li><a href="">Pages</a></li>
            <li class="active">Contacts</li>
        </ul> -->
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container">		
	<div class="row margin-bottom-30">
    	<div class="col-md-6 md-margin-bottom-40">
            <p>Potatoes, onions and Maize are the gift of God. Pakistani soil is very lucky to have a very conductive climatic condition to grow Vegetables as well as Maize of different tastes, colors and nature.
 HMZ Food Industries is the most fortunate company of Pakistan, which excels in growing, production, processing and exporting Fresh potatoes, onions and Maize to various parts of the world.
 
HMZ Food Industries are the leading exporters of Fresh Vegetables to the Central Asian States, Russian Fedration, Europe, Far East, Middle East, Sri-Lanka, 
Afghanistan. The specialty of HMZ Food Industries is its trade in Potatoes, Onions and Yellow Maize.
 
Honesty, Hard working and sincerity are the landmark of HMZ Food Industries.
 <blockquote>
    <p>HMZ Food Industries was initially established in 2000 with the name of Sabir Niaz Traders in grain market and Abid Fiaz and co. in Fruit and Vegetables market. 
And it mainly focused in growing, packing and transportation of fresh potatoes to the various parts of Pakistan.</p>
</blockquote>

 
<p>We have our own agricultural land that is used for the growing of potatoes, onions and yellow maize.
Later on HMZ Food Industries was incorporated in 2012 with New cold stores having huge storage capacity of  goods,
 Processing Unit, Packing Facility, equipped with Latest high Technology were constructed and 
installed at it at our head office Arifwala, Pakpattan Distt.
</p>
 
<blockquote> 
<p>Our head office is at Lahore and we are investing huge amount in millions to export fresh and standard 
quality potatoes. This enables HMZ Food Industries to multiply its products and exports of Fresh potatoes 
in an easy way and in excellent conditions. Exports of Fresh potatoes of HMZ Food Industries are increasing 
in leaps and bounds and in the year 2012.</p>
</blockquote>
 
HMZ Food Industries has exported its fresh potatoes, onions and maize to Central Asian states through land routs since 5/6 years and it is the specialty of HMZ Food Industries that its products reached
 in the hands of CAS Fresh and in Excellent Condition.
 <p>
HMZ Food Industries has exported its fresh potatoes, onions and maize to Central Asian states through land routs
 since 2/3 years and it is the specialty of HMZ Food Industries that its products reached in the hands of CAS Fresh
 and in Excellent Condition.
HMZ Food Industries has keeps its tradition, with the increase in exports HMZ Food Industries has also expanded its 
structure of Arifwala, Pakpattan Distt. Also installed a new Processing and packing Unit in Arifwala to compete the
 demand of potatoes. HMZ Food Industries are equipped with the latest production techniques, latest machinery, trained 
manpower and own facility of cold storage. In early 2012 HMZ Food Industries has also launched their own Potato processing
facility at Arifwala, Pakpattan Distt.

 </p>
            <!-- Blockquotes -->
            <blockquote>
                <p>HMZ Food Industries has also expanded its network and is dealing in export of some other best quality Fresh vegetables and rice available in Pakistan.</p>
            </blockquote>
        </div>

    	<div class="col-md-6 md-margin-bottom-40">
            <div>
               <!--  <iframe src="http://player.vimeo.com/video/9679622" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>  -->
                <img class="img-responsive margin-bottom-20" src="/assets/machine.jpg" alt="" />
            </div>
        </div>
    </div><!--/row-->

	<!-- Meer Our Team -->
	<div class="headline"><h2>Meet Our Team</h2></div>
    <div class="row team">
        <div class="col-sm-3">
            <div class="thumbnail-style">
                <img class="img-responsive" src="/assets/new/ceo4.jpg" alt="" style="height:225px;" />
                <h3><a>Hafiz Muhammad Zahid</a> <small>Chief Executive Officer</small></h3>
                <p>World is a global village, you can find whatever you want as per your requirement but the best thing is to know what actually your requirement is ! <br/>We shall meet your requirement and avaluate what actually you want.</p>
            </div>
        </div>
<!--  -->
        <div class="col-sm-3">
            <div class="thumbnail-style">
                <img class="img-responsive" src="/assets/new/abid1.png" alt="" style="height:225px;"/>
                <h3><a>Muhammad Abid</a> <small>Marketing & Sales Manager</small></h3>
                <p>We build strong business relationship,
                     maintain quality, focus on customer 
                    requirement
                    , deliver products on time. That's what
                     a business demand.
                     We shall fulfill your demands.</p>
            </div>
        </div>
    </div><!--/team-->
	<!-- End Meer Our Team -->

</div><!--/container-->		
<!--=== End Content Part ===-->
<%= render "footer"%>
<!-- JS Global Compulsory -->           
<script type="text/javascript" src="/assets/hover-dropdown.min.js"></script>
<script type="text/javascript" src="/assets/back-to-top.js"></script>
<script type="text/javascript">
    // jQuery(document).ready(function() {
    //     App.init();
    //     App.initSliders();        
    // });
</script>
<!--[if lt IE 9]>
    <script src="assets/plugins/respond.js"></script>
<![endif]-->

</body>
</html> 

app/views/homes/contact.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->  
<head>
     <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content=""> 
</head> 

<body>

<%= render "header"%> 

<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Our Contacts</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container">     
    <div class="row margin-bottom-30">
        <div class="col-md-9 mb-margin-bottom-30">
            <p>HMZ Food Industries are the leading exporters of Fresh Potatoes, onions
             & Maize to the Central Asian States, Russian Fedration, Europe,
             Far East, Middle East, Sri-Lanka, Afghanistan. The specialty of HMZ Exporters     
             is its trade in Potatoes, onion and Maize.
            </p><br>
            <div class="col-md-9">
            <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=30.345000%2C73.385000", :class=>"img-responsive" %>
            </div>
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            <form action="/homes/message" method="post">
            <label>Name</label>
            <div class="row margin-bottom-20">
                <div class="col-md-7 col-md-offset-0">
                    <input type="text" name="name" class="form-control">
                </div>                
            </div>
            
            <label>Email <span class="color-red">*</span></label>
            <div class="row margin-bottom-20">
                <div class="col-md-7 col-md-offset-0">
                    <input type="text" name="email" class="form-control">
                </div>                
            </div>
            
            <label>Message</label>
            <div class="row margin-bottom-20">
                <div class="col-md-11 col-md-offset-0">
                    <textarea rows="8" class="form-control" name="message" placeholder="Write message here ..."></textarea>
                </div>                
            </div>
            
            <p><button type="submit" class="btn-u">Send Message</button></p>
        </form>
        </div><!--/col-md-9-->
        
        


        <div class="col-md-3 pull-right">
            <!-- Google Map -->
            <div class="headline"><h2>Head Office</h2></div>
            <ul class="list-unstyled who margin-bottom-30">
                <li>Office No 319 sector B 59/c Eden Lane villas, Raiwind Road Lahore</li>
                <li><strong>Cell:</strong> +92 300 694 4309</li>
                <li><strong>Phone:</strong>+92 300 694 9221</li>
                <li><strong>Email:</strong> hmz.industry@gmail.com</li>
            </ul>
        </div>    
        <div class="col-md-3 pull-right">

            <div class="headline"><h2>Arifwala Office</h2></div>
            <ul class="list-unstyled who margin-bottom-30">
                <li>Shop-17 New Sabzi Mandi Arifwala,Pakpattan Distt. , Punjab, Pakistan</li>
                <li><strong>Cell:</strong> +92 300 694 9221</li>
                <li><strong>Email:</strong> hmz.industry@gmail.com</li>
            </ul>
            <!-- End Contacts -->



<strong>Contact on Phone:</strong> 08:00AM to 06:00PM
Email us at any time.
            <!-- Business Hours -->
            <div class="headline"><h2>Business Hours</h2></div>
            <ul class="list-unstyled margin-bottom-30">
                <li><strong>Monday-Friday:</strong> 08:00 AM to 06:00 PM</li>
                <li><strong>Saturday:</strong> 09:00 AM to 02:00 PM</li>
                <li><strong>Sunday:</strong> Closed</li>
            </ul>
            <!-- End Business Hours -->
        </div><!--/col-md-3-->
    </div><!--/row-->        
</div><!--/container-->     
<!--=== End Content Part ===-->

<!--=== Footer ===-->
<%= render "footer"%>  
<!--=== End Footer ===-->

<!-- JS Global Compulsory -->           
<script type="text/javascript" src="/assets/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="/assets/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="/assets/bootstrap/js/bootstrap.min.js"></script> 
<script type="text/javascript" src="/assets/hover-dropdown.min.js"></script> 
<script type="text/javascript" src="/assets/back-to-top.js"></script>
<!-- JS Implementing Plugins -->           
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="assets/plugins/gmap/gmap.js"></script>
<!-- JS Page Level -->           
<script type="text/javascript" src="assets/js/app.js"></script>
<script type="text/javascript" src="assets/js/pages/contact.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        App.initSliders();                
        Contact.initMap();        
    });
</script>
<!--[if lt IE 9]>
    <script src="assets/respond.js"></script>
<![endif]-->

</body>
</html> 

app/views/homes/index.html.erb
<!DOCTYPE html>

    <div id="content" class="col-md-9 col-sm-9 col-xs-12">
      <div class="row carousel-holder">
        <div class="col-md-12">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                  <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner">
                  <div class="item active">
                      <img class="slide-image" src="/assets/maxresdefault.jpg" class="img-responsive" alt="">
                  </div>
                  <div class="item">
                      <img class="slide-image" src="/assets/slider2.jpg" class="img-responsive" alt="">
                  </div>
                  <div class="item">
                      <img class="slide-image" src="/assets/slider4.jpg" class="img-responsive" alt="">
                  </div>
              </div>
              
            
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                 <img class="slide-image" src="/assets/product-img1.jpg" class="img-responsive" alt="">


                <div class="caption">
                <strong>Lathe Machine</strong>
                    <p>BED WIDTH 500 600 660 760 900 1050</p>
                    <p>CENTER HEIGHT 450 500 600 700 800 925</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img class="slide-image" src="/assets/4.jpg" class="img-responsive" alt="">
                <div class="caption">
                    <strong>Grinding Machine</strong>
                    <p>Table size overall   965 x 210   910 x 280</p>
                    <p>Working surface table   525 x 205   650 x 260</p>
                    <p>Grinding capacity   500 x 200   600 x 250</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
               <img class="slide-image" src="/assets/p3.jpg" class="img-responsive" alt="">
                <div class="caption">
                    <strong>Welding Machine</strong>
                    <p>APPLICATIONS :
                        Include upset butt welding of all profiles of wires and flats of iron, steel, alloy and carbon steel, copper, aluminium, brass and other light metals and their alloys.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img class="slide-image" src="/assets/p4.jpg" class="img-responsive" alt="">
                <div class="caption">
                    <strong>Universal Gear Hobing Machine</strong>
                    <p>Gear Hobbing Machine model V-300 is designed for the production of precision Spur, Helical, Worm Gears, Splines, Sprockets, Rachet Wheels & any other form that can be hobbed.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img class="slide-image" src="/assets/p5.jpg" class="img-responsive" alt="">
                <div class="caption">
                    <strong>Sheet Metal Machine</strong>>
                    <p>The Plate and Section Shearing Machines 5S / 13R are versatile in application. The welded construction gives well defined passages for letting sheets and plates pass during shearing operations. A hand pin connects the pair of lever slides with the blade slide. The connection is effected by the insertion of the hand pin in the rear hole for shearing full capacity materials and in the front hole for shearing lighter materials.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <h4><a href="#">Like this template?</a>
            </h4>
            <p>If you like this template, then check out <a target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">this tutorial</a> on how to build a working review system for your online store!</p>
            <a class="btn btn-primary" target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">View Tutorial</a>
        </div>
      </div>
    </div>
  

<%#= render "footer"%>

<!-- JS Global Compulsory -->			
<script type="text/javascript" src="assets/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="assets/bootstrap/js/bootstrap.min.js"></script> 
<!-- JS Implementing Plugins -->           
<!-- JS Page Level -->           
<script type="text/javascript" src="assets/app.js"></script>
<script type="text/javascript" src="assets/owl.carousel.js"></script>
<script type="text/javascript" src="assets/pages/index.js"></script>


</body>
</html>	

app/views/layouts/_content.html.erb
<% flash.each do |name,msg| %>
	<div class="alert alert-<%= name%>">
		<a class="close" data-dismiss="alert">x</a>	
		<%= msg%>
	</div>
<% end %>
<section id="main">
	<div class="container">	
		<aside id="sidebar" class="col-md-3 col-sm-3 col-xs-12" style="margin-top:11px;">
		     <a id="logo" href="index.html">
		        <img src="/assets/logo.png"  class="img-responsive" alt="Caprice" />
		    </a>
	    	<!-- Begin Menu -->
		      <div id="menu" class="menu-v">
		        <ul>
		         <% @categories.each do |category|%>
		            <li><%= link_to "#{category.name}", category_path(category.id)%>
		                 <% if user_signed_in? %>
		                <%= link_to "edit", edit_category_path(category.id)%>
		              <% end %>  
		            </li>
		         <% end %> 
		        </ul>
		      </div>
		    <!-- End Menu -->
	    </aside>
	   <!-- End Sidebar -->

		<%= yield %>
	</div>
</section>

app/views/layouts/_footer.html.erb
<!--=== Footer ===-->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 md-margin-bottom-40">
                <!-- About -->
                <div class="headline"><h2>Home</h2></div>  
                <p class="margin-bottom-25 md-margin-bottom-40">We are Leading all kind of machines Supplier from all over the world.</p>    
            </div><!--/col-md-4-->  
            
            <div class="col-md-4 md-margin-bottom-40">
                <div class="posts">
                    <div class="headline"><h2>About Us</h2></div>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p> 
                </div>
            </div><!--/col-md-4-->
            <div class="col-md-4">
                <!-- Monthly Newsletter -->
                <div class="headline"><h2>Contact Us</h2></div> 
                <address class="md-margin-bottom-40">
                    Tarki Al-Qhtani Eztablishment, Al-jawhara Industrial Area Car Exhibition Near Al-jawhara P.Station  <br/>
                    Cell  : 0507308739 <br/>
                    Phone : 0548070575  <br />
                    Email : subhanallahgrp@yahoo.com</a>
                </address>
            </div><!--/col-md-4-->
        </div><!--/row-->   
    </div><!--/container--> 
</div><!--/footer-->    
<!--=== End Footer ===-->

<!--=== Copyright ===-->
<div class="copyright">
	<div class="container">
		<div class="row">
			<div class="col-md-6">						
	            <p class="copyright-space">
                    2015 &copy; Subhanallah Group. ALL Rights Reserved. 
                    <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a>
                </p>
			</div>
		</div><!--/row-->
	</div><!--/container-->	
</div><!--/copyright-->	
<!--=== End Copyright ===-->

app/views/layouts/_navBarLayout.html.erb
<header id="header"> 
    <!-- Navigation -->
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid"> 
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="#">
            <img  src="/assets/logo.png" class="img-responsive" style="width:250px;"></a> 
            </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                
               <li> <%= link_to "Add Category", new_category_path %></li>
                <li><%= link_to "Add Machine", new_machine_path%></li> 
                <li><%= link_to "About Us", "#"%></li>
                <li><%= link_to "Contact", "#"%></li>
                <li style="padding-top: 13px; padding-bottom: 15px; color:white;">| &nbsp <%= current_user.email %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "About Us", "#"%></li>
                <li><%= link_to "Contact", "#"%></li>
                <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>

            </ul>
          </div>
          <!-- /.navbar-collapse --> 
        </div>
      <!-- /.container-fluid --> 
    </nav>
    </div>
  </header>
 
          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= content_for?(:title) ? yield(:title) : "Subhanllah Group Industry" %></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render :partial=>"layouts/navBarLayout" %>
		<%= render :partial=>"layouts/content" %>
		<%= render :partial=>"layouts/footer" %>
	</body>
</html>

app/views/machines/edit.html.erb
<div class="well" style="width: 36%;margin-top: 2%;margin-left: 29%;">
  <%= form_for @machine, :html => {:multipart => true} do |f| %>
    <%#= f.error_messages %>
     <p>
      <%= f.label :category %><br />
      <%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => 'Select',class: 'form-control') %>
    </p>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name, class: 'form-control', :placeholder=> "Name" %>
    </p>
    <p>
      <%= f.label "Reference" %><br />
      <%= f.text_field :url, class: 'form-control', :placeholder=> "URL" %>
    </p>
     <p>
      <%= f.label :description %><br />
      <%#= f.text_area :description,class: 'form-control' %>
      <%= f.text_area(:description, size: '43x10') %>
    </p>
    <p>
      <%= f.file_field :image %>
    </p>
    <p><%= f.submit class: 'btn btn-primary'%></p>
  <% end %>
</div>

app/views/machines/show.html.erb
    <div id="content" class="col-md-9 col-sm-9 col-xs-12" >
      <div class="row">
        <div class="col-md-12">
          <h4><strong><%= @machine.name%></strong></h4>
          <!-- <p><%#= @machine.description%></p> -->
          <strong><a href='<%= "#{@machine.url}" %>' target="_blank">more details</a></strong>

          <br/><%= link_to "back", category_path(@machine.category.id), class: "btn btn-primary"%>
        </div>
        <div class="col-md-8 pull-right">  
          <%= image_tag @machine.image_url.to_s, class: "img-responsive", alt: "image description" %>
        </div>
      </div>
      <div class="col-md-12">
        <h3>Product Specification</h3>
        <p><%= @machine.description%></p>
      </div>
    </div>